#!/bin/sh -m

#-
# Copyright (C) 2011-2012  Oy L M Ericsson Ab, NomadicLab
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Alternatively, this software may be distributed under the terms of the
# BSD license.
#
# See LICENSE and COPYING for more details.
#

#export PYTHONPATH=$HOME/usr/lib/python2.7/site-packages

if [ x"$1" = x"" ]
then
    FILE=file://$HOME/LipsinForwarding.mp4
else
    FILE=$1
fi

python recv_and_pub.py &
PY_PID=$!
echo "PY_PID="$PY_PID
sleep 0.5
vlc --no-audio --no-video $FILE --sout "#duplicate{dst=std{access=udp,mux=ts,dst=127.0.0.1:44252}"
kill -s INT $PY_PID
sleep 2
kill $PY_PID
