#!/bin/sh -m

#-
# Copyright (C) 2011-2012  Oy L M Ericsson Ab, NomadicLab
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# Alternatively, this software may be distributed under the terms of the
# BSD license.
#
# See LICENSE and COPYING for more details.
#

#export PYTHONPATH=$HOME/usr/lib/python2.7/site-packages

python sub_and_send.py &
PY_PID=$!
echo "PY_PID="$PY_PID
sleep 0.5
vlc udp://@:56492
kill -s INT $PY_PID
sleep 2
kill $PY_PID
