/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class eu_pursuit_client_BlackadderWrapper */

#ifndef _Included_eu_pursuit_client_BlackadderWrapper
#define _Included_eu_pursuit_client_BlackadderWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     eu_pursuit_client_BlackadderWrapper
 * Method:    create_new_ba
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_eu_pursuit_client_BlackadderWrapper_create_1new_1ba
  (JNIEnv *, jobject, jint);

/*
 * Class:     eu_pursuit_client_BlackadderWrapper
 * Method:    delete_ba
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_BlackadderWrapper_delete_1ba
  (JNIEnv *, jobject, jlong);

/*
 * Class:     eu_pursuit_client_BlackadderWrapper
 * Method:    c_publish_scope
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_BlackadderWrapper_c_1publish_1scope
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_BlackadderWrapper
 * Method:    c_publish_item
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_BlackadderWrapper_c_1publish_1item
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_BlackadderWrapper
 * Method:    c_unpublish_scope
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_BlackadderWrapper_c_1unpublish_1scope
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_BlackadderWrapper
 * Method:    c_unpublish_item
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_BlackadderWrapper_c_1unpublish_1item
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_BlackadderWrapper
 * Method:    c_subscribe_scope
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_BlackadderWrapper_c_1subscribe_1scope
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_BlackadderWrapper
 * Method:    c_subscribe_item
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_BlackadderWrapper_c_1subscribe_1item
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_BlackadderWrapper
 * Method:    c_unsubscribe_scope
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_BlackadderWrapper_c_1unsubscribe_1scope
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_BlackadderWrapper
 * Method:    c_unsubscribe_item
 * Signature: (J[B[BB[B)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_BlackadderWrapper_c_1unsubscribe_1item
  (JNIEnv *, jobject, jlong, jbyteArray, jbyteArray, jbyte, jbyteArray);

/*
 * Class:     eu_pursuit_client_BlackadderWrapper
 * Method:    c_publish_data
 * Signature: (J[BB[B[BI)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_BlackadderWrapper_c_1publish_1data
  (JNIEnv *, jobject, jlong, jbyteArray, jbyte, jbyteArray, jbyteArray, jint);

/*
 * Class:     eu_pursuit_client_BlackadderWrapper
 * Method:    c_publish_data_direct
 * Signature: (J[BB[BLjava/nio/ByteBuffer;I)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_BlackadderWrapper_c_1publish_1data_1direct
  (JNIEnv *, jobject, jlong, jbyteArray, jbyte, jbyteArray, jobject, jint);

/*
 * Class:     eu_pursuit_client_BlackadderWrapper
 * Method:    c_nextEvent_direct
 * Signature: (JLeu/pursuit/client/EventInternal;)J
 */
JNIEXPORT jlong JNICALL Java_eu_pursuit_client_BlackadderWrapper_c_1nextEvent_1direct
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     eu_pursuit_client_BlackadderWrapper
 * Method:    c_delete_event
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_eu_pursuit_client_BlackadderWrapper_c_1delete_1event
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
