# Usage in FreeBSD:  make
# Usage in Mac OS X: bsdmake

MAKE=gmake

CXX=g++
CXXFLAGS=-I. -I/usr/local/include -I/opt/local/include
LDFLAGS=-L/usr/local/lib -L/opt/local/lib

.MAIN: all

.DEFAULT:
	$(MAKE) CXX="$(CXX)" CXXFLAGS="$(CXXFLAGS)" LDFLAGS="$(LDFLAGS)" $@
