#!/bin/sh

if [ "$1" = "-h" ] || [ "$1" = "--help" ]
then
    echo $0 removes various files created by \`autoreconf -i\'
    exit
fi

set -x

rm -f configure
rm -f Makefile.in
rm -f config.h.in
rm -rf autom4te.cache
rm -f config/*
rm -f aclocal.m4
rm -f m4/ltsugar.m4
rm -f m4/libtool.m4
rm -f m4/ltversion.m4
rm -f m4/lt~obsolete.m4
rm -f m4/ltoptions.m4
rm -f swig/Makefile.in
rm -f swig/python/Makefile.in
rm -f swig/ruby/Makefile.in
rm -f swig/java/Makefile.in
rm -f bindings/Makefile.in
rm -f bindings/c-binding/Makefile.in

#rm -f m4/lt*.m4
#find . -type f -name 'Makefile.in' -exec rm -fv '{}' \;
