#!/bin/sh
#export RUBYLIB=$HOME/usr/lib/ruby/site_ruby/1.8/x86_64-linux
#export RUBYLIB=$HOME/usr/lib/ruby/site_ruby/1.8/amd64-freebsd8
#export RUBYLIB=$HOME/usr/lib/ruby/site_ruby/1.8/i686-darwin10
irb $@
