all:
	g++ video_publisher.cpp -o video_publisher -lpthread -lssl -lblackadder
	g++ video_subscriber.cpp -o video_subscriber -lpthread -lssl -lblackadder
video_publisher:
	g++ video_publisher.cpp -o video_publisher -lpthread -lssl -lblackadder
video_subscriber:
	g++ video_subscriber.cpp -o video_subscriber -lpthread -lssl -lblackadder
clean:
	rm video_publisher video_subscriber 
