all:
	g++ video_publisher.cpp -o video_publisher -lpthread -lssl -lblackadder -lcrypto
	g++ video_subscriber.cpp -o video_subscriber -lpthread -lssl -lblackadder -lcrypto
video_publisher:
	g++ video_publisher.cpp -o video_publisher -lpthread -lssl -lblackadder -lcrypto
video_subscriber:
	g++ video_subscriber.cpp -o video_subscriber -lpthread -lssl -lblackadder -lcrypto
clean:
	rm video_publisher video_subscriber 
